# Generated by Django 3.0.1 on 2019-12-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20191225_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='ruby', max_length=20),
        ),
    ]
