# Generated by Django 3.0.1 on 2019-12-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20191225_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='jam', max_length=20),
        ),
    ]
