# Generated by Django 3.0.1 on 2019-12-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20191225_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(default='cherry', max_length=20),
        ),
    ]
