# Generated by Django 3.0.1 on 2019-12-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_auto_20191225_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
