# Generated by Django 3.0.1 on 2019-12-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(default=None, max_length=140),
        ),
    ]
